version: '3.0'

volumes:
  jenkins-master-data:
  
networks:
  jenkins:
    driver: bridge
  
services:
  jenkins-master:
    image: jenkins-master
    container_name: jenkins-master
    restart: unless-stopped
    networks:
      - jenkins
    environment:
      - "JAVA_OPTS=-Duser.timezone=Asia/Jerusalem"
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - 'jenkins-master-data:/var/jenkins_home'
      - '/var/run/docker.sock:/var/run/docker.sock'
